name: 'Create env file'
description: 'Create env file'
inputs:
  APP_ENV:
    description: 'APP_ENV (one of): development, staging, production'
    required: true
    default: 'staging'

runs:
  using: 'composite'
  steps:
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
        envkey_EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        file_name: .env.${{ inputs.APP_ENV }}
