name: Create .env.development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-env:
    name: Create .env.development
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: Create envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          envkey_EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          file_name: .env.development

      - name: Run prebuild
        run: pnpm run prebuild
